# Generated by Django 4.2.11 on 2024-03-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_created',
            new_name='create_dtm',
        ),
    ]
