# Generated by Django 4.2.11 on 2024-03-27 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_tag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='create_dtm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
