# Generated by Django 4.2.11 on 2024-03-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_url_create_dtm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
