# Generated by Django 4.2.11 on 2024-03-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_category_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='users.tag'),
        ),
        migrations.AlterField(
            model_name='url',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
