# Generated by Django 4.2.11 on 2024-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_url_tags_alter_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='urls', to='users.tag'),
        ),
    ]
