# Generated by Django 4.2.11 on 2024-03-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_categorie_name_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='name',
            new_name='cate_name',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
