# Generated by Django 4.2.11 on 2024-03-29 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_categorie_user_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_check_dtm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='url',
            name='url_validate',
            field=models.BooleanField(default=True),
        ),
    ]
